commerce_payment.commerce_payment_gateway.plugin.paymaster:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    secret:
      type: string
      label: 'Secret'
    hash_method:
      type: string
      label: 'Hash method'
    description:
      type: string
      label: 'Description'
    vat_product:
      type: string
      label: 'Vat for product'
    vat_shipping:
      type: string
      label: 'Vat for shipping'